#!/usr/bin/env python
from lxml import etree
import subprocess, sys

doc = etree.parse(file('../pdns/docs/pdns.xml'), parser=etree.XMLParser(load_dtd=True))

docvars = set()
pdnsvars = set()

for term in doc.xpath('//chapter[@id="all-settings"]/para/variablelist/varlistentry/term'):
	varname = term.text
	if not varname:
		varname = term[0].tail
	varname = varname.split('=',1)[0]
	varname = varname.split(' ',1)[0]
	docvars.add(varname)

pdns = subprocess.Popen(['../pdns/pdns_server','--no-config','--help'], stderr=subprocess.PIPE)

for line in pdns.stderr:
	if line.startswith('  --'):
		varname = line[4:].split('=')[0].split()[0]
		pdnsvars.add(varname)

if pdnsvars-docvars:
	print "variables in pdns_server --help but not in pdns.xml:"
	print '\n'.join(sorted(pdnsvars-docvars))
	print

if docvars-pdnsvars:
	print "variables in pdns.xml but not in pdns_server --help:"
	print '\n'.join(sorted(docvars-pdnsvars))
	print
